### ISSUE TITLE
Convert data in excel to csv files for carbon dioxide

### ISSUE THREAD

**Issue by nandkishoregurav** [L-Fandangle042/CO2_Emission_Indicator#1]

**Comment by L-Fandangle042** [comment]
Hey Nanda, do you mean the "TOTALS BY COUNTRY" tab in the CO2_YEARLY_DATA Excel file?

I have a working notebook with this converted into a dataframe that's cleaned and has some data analysis performed.

I've created a pull request to upload it to the master branch. 

Thanks man.
